language: node_js

node_js:
  - 8
  - 6

script:
  - npm run build-css
  - npm run build

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
